Fix NoMethodError and the "[Correctable]" label
Because we weren't always initializing our `@corrector`, a NoMethodError
was occurring in `#autocorrect`. Example output from `rubocop --debug`:

```
Scanning redacted.rb
An error occurred while Layout/OrderedMethods cop was inspecting redacted.rb:24:2.
undefined method `correct' for nil:NilClass
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:45:in `autocorrect'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.9.1/lib/rubocop/cop/cop.rb:142:in `block in correction_lambda'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.9.1/lib/rubocop/cop/cop.rb:148:in `dedup_on_node'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.9.1/lib/rubocop/cop/cop.rb:141:in `correction_lambda'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.9.1/lib/rubocop/cop/cop.rb:125:in `emulate_v0_callsequence'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.9.1/lib/rubocop/cop/cop.rb:34:in `block in add_offense'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.9.1/lib/rubocop/cop/base.rb:340:in `correct'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.9.1/lib/rubocop/cop/base.rb:127:in `add_offense'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.9.1/lib/rubocop/cop/cop.rb:33:in `add_offense'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:53:in `block in on_begin'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:92:in `block (2 levels) in consecutive_methods'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:91:in `each'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:91:in `each_cons'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:91:in `block in consecutive_methods'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:90:in `each'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:90:in `consecutive_methods'
/Users/jared/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ordered_methods-0.7/lib/rubocop/cop/layout/ordered_methods.rb:50:in `on_begin'
...
```